# Generated by Django 3.0.5 on 2020-04-21 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_gamesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamesession',
            options={},
        ),
    ]
